### ISSUE TITLE
Les bonnes questions apparaissent lorsqu'on choisi une catégorie

### ISSUE THREAD

**Issue by JBillault** [ComicScrip/lyon-react-mars22-p2g5#49]
# Le besoin

En tant que joueur , je souhaite que les questions soient en rapport avec la catégorie que j'ai choisie.

## Critères et considérations spécifiques

- [ ] Les bonnes questions apparaissent lorsque je choisie la catégorie

#### Actions à réaliser

- se rendre sur la page "Catégorie" accessible depuis l'URL `/Categorie`
- choisir une catégorie de quiz

#### Verifications

- [ ] les questions correspondent bien à la catégorie choisie

## A faire

- [ ] passer des paramètres dans l'url d'appel de l'API 
- [ ] récupérer les bons paramètres du choix de la catégorie, du nb de question et de la difficulté

**Comment by ComicScrip** [comment]
duplicate of https://github.com/ComicScrip/lyon-react-mars22-p2g5/issues/32
