### ISSUE TITLE
Accéder aux Quiz du Carrousel

### ISSUE THREAD

**Issue by timonicolaux** [ComicScrip/lyon-react-mars22-p2g5#67]
# Le besoin

En tant qu'utilisateur je souhaite pouvoir accéder aux Quiz depuis le Carrousel dans la page Catégories (Quiz Wild, Quiz Lyon, Quiz Aléatoire, Quiz Aléatoire difficile)

## Critères et considérations spécifiques

- [ ] Les quiz sont accessibles et fonctionnels depuis le carrousel depuis la page de catégories

#### Actions à réaliser

- Se rendre sur la page de catégories
- Lors ce qu'on clique sur un quiz du carrousel, on est redirigé vers le quiz correspondant

#### Verifications

- [ ] Cliquer sur une catégorie de Quiz du carrousel
- [ ] Vérifier que le Quiz correspondant s'affiche suite à cette action

## A faire

- [ ] Ajouter une liste de questions & réponses aux composants Quiz Wild et Quiz Lyon, ajouter un lien API Trivia aux composants Quiz Aléatoire et Quiz Aléatoire difficile
- [ ] Reparamétrer/modifier le fichier de jeu afin de pouvoir récupérer non seulement les paramètres actuels, mais aussi les nouveaux paramètres de ces Quiz

**Comment by ComicScrip** [comment]
Bonne idée, mais pas prioritaire pour le moment :) 
On s'en reparle une fois que tout le reste fonctionne ?
